### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hp4k1h5** [HP4k1h5/terminordle#1]
- [x] add different wordlists, word lengths as command line options
- [ ] add new game modes
- [x] better info display for joining parties
